rule_select -rule DCHDL_115 -ruleset RTL -policy DC
rule_select -rule DCHDL_178 -ruleset RTL -policy DC
rule_select -rule DCVER_192 -ruleset RTL -policy DC
rule_select -rule DCVER_274 -ruleset RTL -policy DC
rule_select -rule DCVHDL_165 -ruleset RTL -policy DC
rule_select -policy DC -ruleset RTL -rule DCHDL_140_B
rule_select -policy DC -ruleset RTL -rule DCHDL_175
rule_select -policy DC -ruleset RTL -rule DCVER_143
rule_select -policy DC -ruleset RTL -rule DCVER_177
rule_select -policy DC -ruleset RTL -rule DCVER_178
rule_select -policy DC -ruleset RTL -rule DCVER_179
rule_select -policy DC -ruleset RTL -rule DCVER_180
rule_select -policy DC -ruleset RTL -rule DCVER_181
rule_select -policy DC -ruleset RTL -rule DCVER_182
rule_select -policy DC -ruleset RTL -rule DCVER_183
rule_select -policy DC -ruleset RTL -rule DCVER_184
rule_select -policy DC -ruleset RTL -rule DCVER_185
rule_select -policy DC -ruleset RTL -rule DCVER_187
rule_select -policy DC -ruleset RTL -rule DCVER_188
rule_select -policy DC -ruleset RTL -rule DCVER_189
rule_select -policy DC -ruleset RTL -rule DCVER_190
rule_select -policy DC -ruleset RTL -rule DCVER_191
rule_select -policy DC -ruleset RTL -rule DCVER_193
rule_select -policy DC -ruleset RTL -rule DCVER_219
rule_select -policy DC -ruleset RTL -rule DCVER_256
rule_select -policy DC -ruleset RTL -rule DCVER_265
rule_select -policy DC -ruleset RTL -rule DCVER_266
rule_select -policy DC -ruleset RTL -rule DCVER_267
rule_select -policy DC -ruleset RTL -rule DCVER_268
rule_select -policy DC -ruleset RTL -rule DCVER_269
rule_select -policy DC -ruleset RTL -rule DCVER_270
rule_select -policy DC -ruleset RTL -rule DCVER_271
rule_select -policy DC -ruleset RTL -rule DCVER_272
rule_select -policy DC -ruleset RTL -rule DCVER_273
rule_select -policy DC -ruleset RTL -rule DCVER_275
rule_select -policy DC -ruleset RTL -rule DCVER_276
rule_select -policy DC -ruleset RTL -rule DCVER_277
rule_select -policy DC -ruleset RTL -rule DCVER_286
rule_select -policy DC -ruleset RTL -rule DCVER_295
rule_select -policy DC -ruleset RTL -rule DCVER_296
rule_select -policy DC -ruleset RTL -rule DCVER_297
rule_select -policy DC -ruleset RTL -rule DCVER_305
rule_select -policy DC -ruleset RTL -rule DCVER_306
rule_select -policy DC -ruleset RTL -rule DCVER_309
rule_select -policy DC -ruleset RTL -rule DCVER_310
rule_select -policy DC -ruleset RTL -rule DCVER_4
rule_select -policy DC -ruleset RTL -rule DCVER_917
rule_select -policy DC -ruleset RTL -rule DCVER_919
rule_select -policy DC -ruleset RTL -rule DCVER_966
rule_select -policy DC -ruleset RTL -rule DCVER_967
rule_select -policy DC -ruleset RTL -rule DCVER_968
rule_select -policy DC -ruleset RTL -rule DCVER_969
rule_select -policy DC -ruleset RTL -rule DCHDL_109
rule_select -policy DC -ruleset RTL -rule DCHDL_224
rule_select -policy DC -ruleset RTL -rule DCHDL_270
rule_select -policy DC -ruleset RTL -rule DCHDL_326
rule_select -policy DC -ruleset RTL -rule DCHDL_96
rule_select -policy DC -ruleset RTL -rule DCVHDL_111
rule_select -policy DC -ruleset RTL -rule DCVHDL_2
rule_select -policy DC -ruleset RTL -rule DCVHDL_2001
rule_select -policy DC -ruleset RTL -rule DCVHDL_2021
rule_select -policy DC -ruleset RTL -rule DCVHDL_2022
rule_select -policy DC -ruleset RTL -rule DCVHDL_2024
rule_select -policy DC -ruleset RTL -rule DCVHDL_2040
rule_select -policy DC -ruleset RTL -rule DCVHDL_2100
rule_select -policy DC -ruleset RTL -rule DCVHDL_2108
rule_select -policy DC -ruleset RTL -rule DCVHDL_2109
rule_select -policy DC -ruleset RTL -rule DCVHDL_2111
rule_select -policy DC -ruleset RTL -rule DCVHDL_2131
rule_select -policy DC -ruleset RTL -rule DCVHDL_2140
rule_select -policy DC -ruleset RTL -rule DCVHDL_2150
rule_select -policy DC -ruleset RTL -rule DCVHDL_2151
rule_select -policy DC -ruleset RTL -rule DCVHDL_2152
rule_select -policy DC -ruleset RTL -rule DCVHDL_2155
rule_select -policy DC -ruleset RTL -rule DCVHDL_2159
rule_select -policy DC -ruleset RTL -rule DCVHDL_2163
rule_select -policy DC -ruleset RTL -rule DCVHDL_2207
rule_select -policy DC -ruleset RTL -rule DCVHDL_2251
rule_select -policy DC -ruleset RTL -rule DCVHDL_2254
rule_select -policy DC -ruleset RTL -rule DCVHDL_2255
rule_select -policy DC -ruleset RTL -rule DCVHDL_2262
rule_select -policy DC -ruleset RTL -rule DCVHDL_2264
rule_select -policy DC -ruleset RTL -rule DCVHDL_2270
rule_select -policy DC -ruleset RTL -rule DCVHDL_2284
