rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_27
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_3
rule_select -policy FORMALITY -ruleset HARD_CASE -rule FM_1_1
rule_select -policy FORMALITY -ruleset HARD_CASE -rule FM_1_4
rule_select -policy FORMALITY -ruleset HARD_CASE -rule FM_1_5
rule_select -policy FORMALITY -ruleset HARD_CASE -rule FM_1_7
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_15
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_16
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_17
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_19
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_1A
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_1B
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_20
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_21
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_25
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_26
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_5
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_6A
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_8
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_10 
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_12 
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_13 
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_18 
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_4 
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_7 
rule_select -policy FORMALITY -ruleset SIMULATION_MISMATCH -rule FM_2_9 
