rule_deselect -all
rule_select -policy LEDA -rule B_1204 -ruleset CLOCKS
rule_select -policy LEDA -rule C_1201 -ruleset CLOCKS
rule_select -policy LEDA -rule C_1203 -ruleset CLOCKS
rule_select -policy LEDA -rule C_1204 -ruleset CLOCKS
rule_select -policy LEDA -rule B_3010 -ruleset DATA_TYPES
rule_select -policy LEDA -rule B_1001 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule B_1002 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule B_1011 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule C_1000 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule C_1001 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule C_1005 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule C_1007 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule C_1009 -ruleset DESIGN_STRUCTURE
rule_select -policy LEDA -rule C_1406 -ruleset RESETS
rule_select -policy LEDA -rule B_3203 -ruleset EXPRESSIONS
rule_select -policy LEDA -rule B_3208 -ruleset EXPRESSIONS
rule_select -policy LEDA -rule B_3209 -ruleset EXPRESSIONS
rule_select -policy LEDA -rule B_2001 -ruleset RTL_SYNTHESIS
rule_select -policy LEDA -rule B_2011 -ruleset RTL_SYNTHESIS
rule_select -policy LEDA -rule B_3602 -ruleset STATE_MACHINES
rule_select -policy LEDA -rule B_3604 -ruleset STATE_MACHINES
rule_select -policy LEDA -rule B_3605_A -ruleset STATE_MACHINES
rule_select -policy LEDA -rule B_3605_B -ruleset STATE_MACHINES
rule_select -policy LEDA -rule B_3607 -ruleset STATE_MACHINES
rule_select -policy LEDA -rule B_3408 -ruleset STATEMENTS
rule_select -policy LEDA -rule B_3409 -ruleset STATEMENTS
rule_select -policy LEDA -rule B_3410 -ruleset STATEMENTS
rule_select -policy LEDA -rule B_3416 -ruleset STATEMENTS
rule_select -policy LEDA -rule B_3417 -ruleset STATEMENTS
rule_select -policy LEDA -rule B_3419 -ruleset STATEMENTS
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK03
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK04
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK05
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK09
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK13
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK14
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK15
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK22
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK23
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK31
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK33
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK35
rule_select -policy DESIGN -ruleset CLOCKS -rule NTL_CLK38
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON01
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON02
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON03
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON04
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON05
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON06
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON08
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON09
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON10
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON15
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON18
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON19
rule_select -policy DESIGN -ruleset CONNECTIVITY -rule NTL_CON22
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT07
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT08
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT09
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT11
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT13
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT14
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT15
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT16
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT22
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT23
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT24
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT25
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT26
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT31
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT38
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT39
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT40
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT42
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT45
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT50
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT52
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT54
rule_select -policy DESIGN -ruleset DFT -rule NTL_DFT55
rule_select -policy DESIGN -ruleset LANGUAGE -rule NTL_LAN24
rule_select -policy DESIGN -ruleset RESETS -rule NTL_RST04
rule_select -policy DESIGN -ruleset RESETS -rule NTL_RST07
rule_select -policy DESIGN -ruleset RESETS -rule NTL_RST12
rule_select -policy DESIGN -ruleset RESETS -rule NTL_RST13
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR07
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR11
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR12
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR13
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR16
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR27
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR29
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR34
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR45
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR52
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR61
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR63
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR72
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR74
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR79
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR85
rule_select -policy DESIGN -ruleset STRUCTURE -rule NTL_STR90
rule_select -policy RMM_RTL_CODING_GUIDELINES -rule R_521_10 -ruleset BASIC_CODING_PRACTICES
rule_select -policy RMM_RTL_CODING_GUIDELINES -rule R_529_1 -ruleset BASIC_CODING_PRACTICES
rule_select -policy RMM_RTL_CODING_GUIDELINES -rule G_546_1 -ruleset CLOCKS_AND_RESETS
rule_select -policy RMM_RTL_CODING_GUIDELINES -rule G_551_1_A -ruleset CODING_FOR_SYNTHESIS
rule_select -policy RMM_RTL_CODING_GUIDELINES -rule G_551_1_B -ruleset CODING_FOR_SYNTHESIS
