Date:Thu Sep 17 11:42:28 AM CST 2009
Input command file generated by LEDA

#VERILOGCompiler	/ecad/synopsys/leda_b200806/linux/bin/ve -M +no_lvs_env -c -z -p2 -i -k01 -log /export/home/user/wangyl/mini_rtlqa_env/digital/impl/leda/run_dir/leda-logs/compiler.log -full_log -swarning +max_case+8 +max_casexz+8 -maxviolations 100 -top des -save_uniquified_modules
#VHDLCompiler	/ecad/synopsys/leda_b200806/linux/bin/v -M +no_lvs_env  -c -z -i -k93e  -full_log -swarning -maxviolations 100
#HOMELESS	LEDA_WORK
#Makefile-Name	LEDA_Makefile
#Makelibs-Name	LEDA_Makelibs
#Project-Name	/export/home/user/wangyl/mini_rtlqa_env/digital/impl/leda/run_dir/leda.pro

#VHDLSuffixes
#End

#VHDLSuffixes
#End

#VERILOGSuffixes
v -
ve -
inc -
#End
#Mappings
#End
#Files LEDA_WORK
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/des_cop.v
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/des_dat.v
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/des_iv.v
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/des_key.v
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/tiny_des_round.v
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/tiny_des.v
   /export/home/user/wangyl/mini_rtlqa_env/digital/hdl/des/des.v
#End

#VERILOGSuffixes
#End

#VHDLSuffixes
#End
#Mappings
#End
#Files LEDA_WORK
#End
#Resources
   STD $LEDA_PATH/linux/resources/resource_93/STD 
   IEEE $LEDA_PATH/linux/resources/resource_93/IEEE 
   SYNOPSYS $LEDA_PATH/linux/resources/resource_93/SYNOPSYS 
   SNPS_EXT $LEDA_PATH/linux/resources/resource_93/SNPS_EXT 
#End
